{% set name = "basedtyping" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/basedtyping-{{ version }}.tar.gz
  sha256: 9573bfd2ab36d2179049fc8ec16f56b1b3bee42598c05097e4753ba9676fc407

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.8,<4.0.0
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0

test:
  imports:
    - basedtyping
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Utilities for basedmypy
  description: It's recommended to use basedmypy when using basedtyping, as there are specialised adaptations made to basedmypy to support some functionality of this package.
  home: https://github.com/KotlinIsland/basedtyping
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
