{% set name = "basedtyping" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/basedtyping-{{ version }}.tar.gz
  sha256: d7600917ec9f232c9eb4266916c2ea5a4719ffca59fb7902fc96fd59a4678110

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.8
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0

test:
  imports:
    - basedtyping
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Utilities for basedmypy
  description: It's recommended to use basedmypy when using basedtyping, as there are specialised adaptations made to basedmypy to support some functionality of this package.
  home: https://github.com/KotlinIsland/basedtyping
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
